#used to upload to aws lambda only
service: dynamic-image-generator

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-apigw-binary
  - serverless-apigwy-binary
#   - serverless-offline

custom:
  #include here the types of images you'll be returning
  apigwBinary:
    types:
      - 'image/jpeg'
      - 'image/jpg'
      - 'image/png'
      - '*/*'

package:
  # exclude:
  #   - config/.env.stg
  #   - config/.env.pro
  #make sure to include fonts/images/extra assets needed that aren't ts files
  include:
    - api/_fonts/*
    - api/_templates/insta-story/images/*

functions:
  instaStory:
    handler: api/lambda_handler.instaStory
    memorySize: 3008
    timeout: 10
    events:
      - http:
          path: instaStory
          method: get
          contentHandling: CONVERT_TO_BINARY #converts images to binary reducing image size