#used to upload to aws lambda only
service: dynamic-image-generator

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
#   - serverless-offline

package:
  # exclude:
  #   - config/.env.stg
  #   - config/.env.pro
  include:
    - api/_fonts/*
    - api/_templates/insta-story/images/*

functions:
  instaStory:
    handler: api/lambda_handler.instaStory
    memorySize: 3008
    events:
      - http:
          path: instaStory
          method: get