const jesus = {
resource: '/instaStory',
path: '/instaStory',
httpMethod: 'GET',
headers: {
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'Accept-Encoding': 'gzip, deflate, br',
  'Accept-Language': 'en-US,en;q=0.9',
  'CloudFront-Forwarded-Proto': 'https',
  'CloudFront-Is-Desktop-Viewer': 'true',
  'CloudFront-Is-Mobile-Viewer': 'false',
  'CloudFront-Is-SmartTV-Viewer': 'false',
  'CloudFront-Is-Tablet-Viewer': 'false',
  'CloudFront-Viewer-Country': 'US',
  Host: 'zs8l2sx283.execute-api.us-east-1.amazonaws.com',
  'sec-ch-ua': '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
  'sec-ch-ua-mobile': '?0',
  'sec-fetch-dest': 'document',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'none',
  'sec-fetch-user': '?1',
  'upgrade-insecure-requests': '1',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
  Via: '2.0 d5751eb4ade84ec583fd46fe452b9152.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'bFJFF7ctVsdK-s3fSrNAsQ3AS2uD7WQjjwvikMNlzXMQt4PZ7g7waA==',
  'X-Amzn-Trace-Id': 'Root=1-606f644a-6f175cad46519a7d0449ea19',
  'X-Forwarded-For': '24.243.157.19, 70.132.35.76',
  'X-Forwarded-Port': '443',
  'X-Forwarded-Proto': 'https'
},
multiValueHeaders: {
  Accept: [
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
  ],
  'Accept-Encoding': [ 'gzip, deflate, br' ],
  'Accept-Language': [ 'en-US,en;q=0.9' ],
  'CloudFront-Forwarded-Proto': [ 'https' ],
  'CloudFront-Is-Desktop-Viewer': [ 'true' ],
  'CloudFront-Is-Mobile-Viewer': [ 'false' ],
  'CloudFront-Is-SmartTV-Viewer': [ 'false' ],
  'CloudFront-Is-Tablet-Viewer': [ 'false' ],
  'CloudFront-Viewer-Country': [ 'US' ],
  Host: [ 'zs8l2sx283.execute-api.us-east-1.amazonaws.com' ],
  'sec-ch-ua': [
    '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"'
  ],
  'sec-ch-ua-mobile': [ '?0' ],
  'sec-fetch-dest': [ 'document' ],
  'sec-fetch-mode': [ 'navigate' ],
  'sec-fetch-site': [ 'none' ],
  'sec-fetch-user': [ '?1' ],
  'upgrade-insecure-requests': [ '1' ],
  'User-Agent': [
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36'
  ],
  Via: [
    '2.0 d5751eb4ade84ec583fd46fe452b9152.cloudfront.net (CloudFront)'
  ],
  'X-Amz-Cf-Id': [ 'bFJFF7ctVsdK-s3fSrNAsQ3AS2uD7WQjjwvikMNlzXMQt4PZ7g7waA==' ],
  'X-Amzn-Trace-Id': [ 'Root=1-606f644a-6f175cad46519a7d0449ea19' ],
  'X-Forwarded-For': [ '24.243.157.19, 70.132.35.76' ],
  'X-Forwarded-Port': [ '443' ],
  'X-Forwarded-Proto': [ 'https' ]
},
queryStringParameters: null,
multiValueQueryStringParameters: null,
pathParameters: null,
stageVariables: null,
requestContext: {
  resourceId: 'n4us56',
  resourcePath: '/instaStory',
  httpMethod: 'GET',
  extendedRequestId: 'deybmEcYIAMFpMw=',
  requestTime: '08/Apr/2021:20:15:06 +0000',
  path: '/dev/instaStory',
  accountId: '761236050644',
  protocol: 'HTTP/1.1',
  stage: 'dev',
  domainPrefix: 'zs8l2sx283',
  requestTimeEpoch: 1617912906194,
  requestId: '8aeb984e-b56d-485c-81fb-0a77960dfb56',
  identity: {
    cognitoIdentityPoolId: null,
    accountId: null,
    cognitoIdentityId: null,
    caller: null,
    sourceIp: '24.243.157.19',
    principalOrgId: null,
    accessKey: null,
    cognitoAuthenticationType: null,
    cognitoAuthenticationProvider: null,
    userArn: null,
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
    user: null
  },
  domainName: 'zs8l2sx283.execute-api.us-east-1.amazonaws.com',
  apiId: 'zs8l2sx283'
},
body: null,
isBase64Encoded: false
}